export PATH="$HOME/.nodebrew/current/bin:$PATH"
export GOROOT=$HOME/go_appengine/goroot/
export GOPATH=$HOME/go_appengine/gopath/
export PATH=$PATH:$GOROOT/bin/
export APPENGINE_DEV_APPSERVER=$HOME/go_appengine/dev_appserver.py
export PATH=$PATH:/opt/local/bin:/opt/local/sbin/
export MANPATH=$MANPATH:/opt/local/man
export PATH="$(brew --prefix homebrew/php/php70)/bin:$PATH"
export LD_LIBRARY_PATH=/usr/local/lib
